### ISSUE TITLE
Contains Method does not Delivers True

### ISSUE THREAD

**Issue by StSchnell** [mihaifm/linq#102]
Thank you very much for this great library.

These days I tried a few methods, including the Contains method. Here my code, which delivers false:

<pre>var numbers = Enumerable.from([
  {number: 10},
  {number: 9},
  {number: 8},
  {number: 7},
  {number: 6}
]);

console.log(JSON.stringify(numbers.contains({number: 9}))); // => false</pre>

I expected true here. Is my approach wrong here?

Thanks for hints and tips.

**Comment by M0ns1gn0r** [comment]
JavaScript does shallow comparison, only primitive types can be compared directly `9 === 9 // true`. You create two object instances which are always different: `{number: 9} === {number: 9} // false`.

**Comment by StSchnell** [comment]
Thank you very much @M0ns1gn0r for this clarification.
