### ISSUE TITLE
No minified package version on bower.

### ISSUE THREAD

**Issue by Mistrall** [mihaifm/linq#11]
Can we have mininifed js file?

**Comment by mihaifm** [comment]
I merged your changes, I will pubish to npm when I get the chance.
I'm not sure what to do with the version, I will probably use a different tag from the Codeplex library, since npm doesn't allow publishing with the same version anymore.

**Comment by Mistrall** [comment]
Tag is ok, bower understands references like this: 
bower install https://github.com/mihaifm/linq#tag

**Comment by mihaifm** [comment]
Published to npm as version 3.0.5. It should be available in bower as well.

cheers

**Comment by Mistrall** [comment]
Thanks a lot!
