### ISSUE TITLE
Differences with docs?

### ISSUE THREAD

**Issue by grofit** [mihaifm/linq#14]
I am not entirely sure where this should go, as really this is just a republish of the codeplex one, but given codeplex is pretty much dead I am not sure where to put it.

Anyway the docs on the side show `SingleOrDefault(default, predicate)` however the code in here is `singleOrDefault(predicate, default)`.

So is there any sort of idea if this is now going to become the maintained build or should this be raised on codeplex?

**Comment by mihaifm** [comment]
Sorry for the delayed response.

Since the codeplex code doesn't appear to be maintained any longer, I think it's safe to have changes here. I will try to contact the original author as well.

**Comment by M0ns1gn0r** [comment]
Look like this one  is related to https://github.com/mihaifm/linq/issues/20

**Comment by M0ns1gn0r** [comment]
As far as I know, the goal of this project is to mimic the C#'s LINQ implementation which has only two overloads: with no arguments and with a single - the predicate. The overload with a default value added to `linqjs` is consistent in keeping the order of arguments: the predicate goes first, too.
