### ISSUE TITLE
Version in bower.json does not correspond to released version

### ISSUE THREAD

**Issue by Maddemacher** [mihaifm/linq#16]
Version in bower.json needs to be bumped to 3.0.5

{
  "name": "linqjs",
  **"version": "1.0.0",** //Change to 3.0.5
  "main": "linq.js",
  "ignore": [
    "**/.*",
    "extensions",
    "test",
    "*.md",
    "CHANGELOG",
    "package.json"
  ],
  "homepage": "https://github.com/mihaifm/linq",
  "_release": "6b76ff6f5f",
  "_resolution": {
    "type": "branch",
    "branch": "master",
    "commit": "6b76ff6f5f77d3a4f7a7812bb9a979536f7e5e78"
  },
  "_source": "git://github.com/mihaifm/linq.git",
  "_target": "*",
  "_originalSource": "linqjs",
  "_direct": true
}

**Comment by mihaifm** [comment]
thanks for pointing this out.
