### ISSUE TITLE
Select specific keys with their values.

### ISSUE THREAD

**Issue by BoudaSolution** [mihaifm/linq#18]
How can I select a group of specific values with their keys? 
I want to able to perform a query similar to "select id, name, ... from table"
meaning I want the result to be an array only containing the fields I chose.
Thanks

**Comment by apemost** [comment]
var table = [
  {id: 1, name: 'n1', age: 11},
  {id: 2, name: 'n2', age: 12},
  {id: 3, name: 'n3', age: 13}
];

var results  = Enumerable.from(table).select(x => ({id: x.id, name: x.name})).toArray();
