### ISSUE TITLE
Typescript does not work

### ISSUE THREAD

**Issue by deadmann** [mihaifm/linq#19]
i use typing and linq js ver 3.0.4-beta5
On TS, when i write codes, i have no issue, on client, when i launch on browser, i get this error:

angular.min.js:118 ReferenceError: Enumerable is not defined

and when i traced the linq.js file: it goes to the first if: 
this one:
```
// module export
    if (typeof define === Types.Function && define.amd) { // AMD
        define("linqjs", [], function () { return Enumerable; });
    }
```

Would you fix it?

**Comment by mihaifm** [comment]
We includede the typescript file, can you check if this is still a problem?

thanks

**Comment by deadmann** [comment]
i some how get it to work, 

hopefully next time, thanks for hard work

**Comment by mihaifm** [comment]
A new version has been published to npm, that should support typescript. 
Thanks for pointing out these issues.
