### ISSUE TITLE
¿Type definitions?

### ISSUE THREAD

**Issue by sant123** [mihaifm/linq#21]
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/13324

Thanks.

**Comment by mihaifm** [comment]
I'll try to include these when I get the chance. A pull request is also welcomed.

**Comment by sant123** [comment]
I wanted to hear that 😄 

https://github.com/mihaifm/linq/pull/22

**Comment by mihaifm** [comment]
I merged it but removed the jquery file, I don't think that's needed.

thanks for your help

**Comment by sant123** [comment]
You welcome ☺ ☺ ☺ ☺
