### ISSUE TITLE
Are you accepting new features/fixes?

### ISSUE THREAD

**Issue by adamburgess** [mihaifm/linq#25]
e.g. https://github.com/mihaifm/linq/issues/20 for a bug/fix
I also wanted to add [iterator support](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Iteration_protocols) so I could use for..of directly instead of using toArray first.

I only ask as this is a copy of codeplex's version but with a few npm fixes, right?
This repo seems to be the most used with 5000 monthly installs, and I personally use it a lot (well, I use a 'fork' (not actually a fork in the git sense) with iterator support), so I'd like to pull some changes in

**Comment by mihaifm** [comment]
yes, new features are more than welcomed...feel free to contribute

**Comment by adamburgess** [comment]
awesome! I'll open some PRs.
