### ISSUE TITLE
Publish latest to NPM

### ISSUE THREAD

**Issue by codeandcats** [mihaifm/linq#32]
Hi @mihaifm,

Can you please publish master to npm?

I'm using linq in my TypeScript project with `noImplicitAny` enabled and currently the compiler errors on the typings for linq 3.0.7.

```
node_modules/linq/linq.d.ts(29,75): error TS7006: Parameter 'element' implicitly has an 'any' type.

node_modules/linq/linq.d.ts(37,5): error TS7010: 'constructor', which lacks return-type annotation, implicitly has an 'any' return type.
```

This is actually fixed in master but it hasn't been published to npm yet. Could you please publish to npm?

Thanks

**Comment by mihaifm** [comment]
done
