### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by mihaifm** [mihaifm/linq#34]
Hi everyone

I contacted the original author of this library and he mentioned that he is no longer maintaining it.
I initially created this repository to add his library to npm, but since then a small number of improvements have been added.
The code is stable, but it could use some enhancements like using the new ecmascript lambdas and all that good stuff.

Unfortunatelly I don't have the time to further maintain this as well, so if anyone wants to contribute let me know here.

thanks

**Comment by M0ns1gn0r** [comment]
I can help you in responding to issues/PRs, but I doubt that I'll do any huge improvements to the lib. Mainly because I don't use it that heavily myself.

Regarding lambdas specifically: I don't think it's a good idea to start using them because it would limit the lib's usage to only the supporting browsers.

**Comment by mihaifm** [comment]
cool, thanks!

**Comment by sant123** [comment]
Hi @mihaifm ,I want to support it ☺

**Comment by ENikS** [comment]
Do you want to merge package with [linq-es2015](https://www.npmjs.com/package/linq-es2015)?

**Comment by sant123** [comment]
Sounds good @ENikS!

**Comment by mihaifm** [comment]
Hi @ENikS, nice library there. There seem to be a few linq implementations out there, at the moment.
How would this work more exactly..the merge ?

**Comment by ENikS** [comment]
I will take over and merge code from both into one lib. I'll create compatibility layer to keep existing users happy and continue on with unified lib.

**Comment by INGCRENGIFO** [comment]
Super!!!!

**Comment by ivanlopezmolina** [comment]
@ENikS Hi, did you do the merge? if not which library do you recommend?

**Comment by ENikS** [comment]
@ivanlopezmolina 
This library is dead at the moment. The owners stopped updating it and did not respond to my proposal to merge it into one common library.  

I'd go with [this one](https://www.npmjs.com/package/linq-es2015)

**Comment by ivanlopezmolina** [comment]
@ENikS ok cool, thanks.

**Comment by mihaifm** [comment]
Hi, sorry for not answering.
I think this would be too much of a hassle. The library is quite simple as it it right now, I'm not planning to add new features, I'll only fix issues if they come up. For any new functionality people can use your library.

**Comment by ENikS** [comment]
@mihaifm  Sounds good 👍

**Comment by ENikS** [comment]
@ivanlopezmolina Yea, the name is not the best but 'linq' was already taken.
