### ISSUE TITLE
Hi! Is this repo in npm?? 

### ISSUE THREAD

**Issue by jairorudas** [mihaifm/linq#35]
Hi, I`am migrating from bower to npm, I looking for the same repository in npm, but I found severals with other tag version. 

Is this repo in npm? 
if yes, Why is the url?

Thanks for your help.

**Comment by mihaifm** [comment]
This is the first result when you search `npm find linq`. Just do `npm install linq` as mentioned in the readme.

**Comment by jairorudas** [comment]
Thanks you so much!
