### ISSUE TITLE
【BUG】FirstOrDefault Always First Data，ignore Where condition

### ISSUE THREAD

**Issue by xingwen1987** [mihaifm/linq#39]
RT，@3.0.4，FirstOrDefault Method Always Return First Data，ignore Where condition。

**Comment by xingwen1987** [comment]
这个问题从 codeplex 版本就一直存在，到目前为止，依然没有解决，Orz。。。

**Comment by alexinea** [comment]
the signatures for the *FirstOrDefault* function is

```
// Overload:function(defaultValue)
// Overload:function(defaultValue,predicate)
```

so, @xingwen1987 , you should written as:
```
var result = Enumerable.From(someCollection).firstOrDefault(null, "foo => foo == 'bar' ");
```

**Comment by alexinea** [comment]
@mihaifm, I think the signature `function(predicate, defaultValue)` is better than `function(defaultValue,predicate)`, for it is much closer to C# LINQ.

**Comment by mihaifm** [comment]
Which version are you looking at? It's like this in the code:

`Enumerable.prototype.firstOrDefault = function (predicate, defaultValue) {`

https://github.com/mihaifm/linq/blob/master/linq.js#L1861

**Comment by alexinea** [comment]
copy that... I just upgraded to the latest version, thx a lot ( • ̀ω•́ )✧

**Comment by mihaifm** [comment]
cool, no problem

**Comment by xingwen1987** [comment]
@mihaifm OK，I'll update my project。
