### ISSUE TITLE
Incompatible with Webpack/Typescript/Angular

### ISSUE THREAD

**Issue by mtman** [mihaifm/linq#41]
If I import it,
```
import 'linq';
```
I get intellisense, but it doesn't compile:
```
'Enumerable' refers to a UMD global, but the current file is a module. Consider adding an import instead.
```

Used with: Webpack, Angular 4, Typescript

**Comment by Schenn** [comment]
Const enumerable = import("linq")

**Comment by mtman** [comment]
Works, thanks. I can also use
```
import * as Enumerable from 'linq';
```
which works with es2015 modules.
