### ISSUE TITLE
where is the repo for ng2-linq

### ISSUE THREAD

**Issue by katesky** [mihaifm/linq#48]
I see that your package is in npm , but there are no links to the repo, can you please share it?

**Comment by mihaifm** [comment]
Hi

That library (ng2-linq) is not related to this git repo, it was build using the original linq.js library (the one  published on Codeplex) with some minor changes for Angular, I guess.
As far as I know, you don't need a git repo to publish to npm, so it probably doesn't have one. 

You can use this library instead if you feel the need, just do `npm install linq`, it should work with Angular. If not, just submit an issue.
