### ISSUE TITLE
can't figure out how to create enumerable from javascript Iterable

### ISSUE THREAD

**Issue by jmagaram** [mihaifm/linq#51]
How do I get a javascript Iterable into your library? Should be simple.

    function* words() : Iterable<string> {
        yield "abc";
        yield "def";
    }

    let x = Linq.from(words()); // does not work

**Comment by mihaifm** [comment]
This is now fixed, you can do `Linq.from(words())` which is much better than converting to Array, since you can work with infinite iterables.

540699b682ae45d5d63679cc4d9171bf655d065c
