### ISSUE TITLE
can't find updated version on cdn; can't install linq from bower

### ISSUE THREAD

**Issue by ellisonch** [mihaifm/linq#57]
I'm trying to find minified and not minified versions of linq that I can use in a browser.  Ideally I could just grab this off of a cdn, but it seems like the latest (`https://cdnjs.com/libraries/linq.js`) is 2.2.0.2 and you're on version 3 now.

I couldn't find anything in the readme about using this in the browser, but I saw in another issue that "bower should work".  I've never heard of bower, but I gave it a shot.  When I run
```
$ bower install linq
```
I get
```
fatal: repository 'https://github.com/mihaifm/linq/blob/master/linq.js.git/' not found
```

Is there any way to easily use the latest version in my browser?

**Comment by mihaifm** [comment]
No It’s not uploaded to any CDN

**Comment by ellisonch** [comment]
This looks good!  You should probably mention this, or something related, in your readme.  I know nothing of npm, and only want to use this library on the web.  I looked for a single .js file, but couldn't find it in the repo.  I didn't even know jsdelivr existed.

**Comment by mihaifm** [comment]
Added CDN availability links in the readme
