### ISSUE TITLE
bower.json is incomplete

### ISSUE THREAD

**Issue by DR9885** [mihaifm/linq#6]
when using yeoman, it doesn't install linq.js as a vendor. This is only because the 'bower.json' file is missing 'main'... I solved it by changing it to this...

{
  "name": "linqjs",
  "homepage": "https://github.com/mihaifm/linq",
  "_release": "6b76ff6f5f",
  "_resolution": {
    "type": "branch",
    "branch": "master",
    "commit": "6b76ff6f5f77d3a4f7a7812bb9a979536f7e5e78"
  },
  "_source": "git://github.com/mihaifm/linq.git",
  "_target": "*",
  "_originalSource": "linqjs",
  "_direct": true,
  "main": "./linq.js"
}

**Comment by dumbguy5689** [comment]
Getting this error today when ````bower install linq  `````

**Comment by arjanvanderleden** [comment]
bower install linqjs might solve this problem
(instead of bower instal linq)

**Comment by M0ns1gn0r** [comment]
Bower seems to be deprecated. From their website:
> While Bower is maintained, we recommend using Yarn and Webpack for front-end projects

Would it be better to drop its support by deleting `bower.json` from the repo?

**Comment by mihaifm** [comment]
yea, let's drop support for it, thanks for pointing it out. 👍
