### ISSUE TITLE
group by with sum producing wrong results

### ISSUE THREAD

**Issue by manish-shukla01** [mihaifm/linq#60]
has someone else seen this. i have large amount of data on which i am doing group by operations..like (1500 rows of data) and when i do group by it does not produce the correct result. it adds the numeric column correctly but puts the amount in wrong key. i tried doing it and matching wit excel pivot table and my results are not tying. has anyone else seen it?

**Comment by M0ns1gn0r** [comment]
It would be nice to see a reproduction.

**Comment by Schenn** [comment]
Does the data have any javascript reserved words as keys?

**Comment by manish-shukla01** [comment]
between thank you @Schenn  and @M0ns1gn0r
