### ISSUE TITLE
ES6 Iterable 

### ISSUE THREAD

**Issue by xmedeko** [mihaifm/linq#65]
As a former C# developer I like your library. Just want to know, any plans to use ES6 Iterable instead of custom Enumerable? If you want to support old browsers, would it be possible to have Enumerables to use Iterables under the hood for modern browsers? Also relates to #51 

Thanks

**Comment by mihaifm** [comment]
Iterable interface for the Enumerable object has been added in this pull request https://github.com/mihaifm/linq/pull/62, in the sense that you can do `for..of` on an Enumerable object.

But I suppose you're looking for a way to initialize Enumerable from an Iterable object, as described in #51? I think it can be done.

**Comment by mihaifm** [comment]
This is now resolved: 540699b682ae45d5d63679cc4d9171bf655d065c. Can you help verifying the fix?

You can now initialize the Enumerable from an iterable object, so the scenario from #51 should now work:

```
function* words() {
    yield "abc";
    yield "def";
}

console.log(Enumerable.from(words()).toArray()); // ["abc", "def"]
```

`Symbol.iterator` was available before, so Enumerable is also an Iterable object where the code requires. Now it works both ways (_initialize_ from Iterable and _become_ an Iterable):

```
for (var a of Enumerable.from(words())) {
    console.log(a);
}
```
The good part is that it doesn't use an array internally, so it works with infinte iterables...which is pretty sweet.

```
function* countToInfinity() {
    var index = 0;
    while (true)
        yield index++;
}

Enumerable.from(countToInfinity()).where(v => v%2 == 0).forEach(x => console.log(x));
```

This will display all even numbers to infinity.

**Comment by xmedeko** [comment]
Yeah, it works perfect, thanks.

Just you can use `Utils.hasNativeIteratorSupport()` in `Enumerable.from`:
```js
            // iterable object
            if (Utils.hasNativeIteratorSupport)
            // orig code: if (typeof Symbol !== 'undefined' && typeof obj[Symbol.iterator] !== 'undefined') {
```

**Comment by mihaifm** [comment]
Cool. Not quite the same, `hasNativeIteratorSupport` checks the global Symbol object, basically a feature check for the browser/node. The new code checks the object we're initializing from, making sure it's iterable.

I'll publish to npm later today, thanks for helping out with this.

**Comment by xmedeko** [comment]
Ah, I see, thanks for explanation.
