### ISSUE TITLE
Broken with node v0.10.29

### ISSUE THREAD

**Issue by gdm85** [mihaifm/linq#7]
I cannot manage to convert an array to Enumerable.

Enumerable.from() keeps returning an empty object ``{}``

This is the output I get from sample.js:

```
first step of Lambda Expression


Scope of lambda expression


from(Object) -> convert to keyvaluePair

foo:a
bar:100
foobar:true

forEach (continue and break)

1:foo
3:foo
5:foo

Grouping and ref/value comparen

false
false
------
------

Regular Expression matches

0 : abcd
1 : c
index : 0
input : abcdefgABzDefabgdg
toString() : abcd,c
---
0 : ABzD
1 : z
index : 7
input : abcdefgABzDefabgdg
toString() : ABzD,z
---
0 : abgd
1 : g
index : 13
input : abcdefgABzDefabgdg
toString() : abgd,g
---

LazyEvaluation and InfinityList

57

Dictionary

zzz
huga
a:zzz
b:huga

Nondeterministic Programs

```

Please also add a reference output and/or a unit test.

As you can see from this part:
```
Grouping and ref/value comparen

false
false
------
------
```

The Enumerable.from() is not working

**Comment by olsonpm** [comment]
mihaifm - first of all, thanks a ton for providing this via npm

To answer the above question, the issue is with ".log()".  the following code works fine

```
var a = Enumerable.range(1, 3)
	.select(function(value, index) { return index + ':' + value })
	.toArray();

console.log(a);	
```

**Comment by mihaifm** [comment]
thanks, I'll probably update the samples/tests to call `log` in this way.

**Comment by mihaifm** [comment]
It seems like the `log` method returns an Enumerable object, so in order to have it printed it you need to call either `toJoinedString` or `toJSONString`, depending on your preferences.

I updated `tutorial.js` to reflect this. Let me know if there are still issues. 
(and sorry it took so long)
