### ISSUE TITLE
How to use.

### ISSUE THREAD

**Issue by GeorGeWzw** [mihaifm/linq#71]
Your example is in uppercase, but it is in lowercase when used. I feel that your example should be adjusted to lowercase.

For example, your example  is （Enumerable.Range(1, 10).Where(delegate(int i) { return i % 3 == 0; })）

But I actually use （Enumerable.from(array).where("x=>x.name=='删除'").toArray();）
![微信截图_20191206170242](https://user-images.githubusercontent.com/46982191/70310298-41466380-184a-11ea-8226-f5ac680d74f5.png)

Otherwise, report wrong.

**Comment by M0ns1gn0r** [comment]
If you mean the example given in the README.md, it contains two parts: the equivalent in **\_C#\_** and how it supposed to be done in linq.js. 

```
// C# LINQ - lambda
Enumerable.Range(1, 10).Where(i => i % 3 == 0).Select(i => i * 10);

// linq.js - arrow function
Enumerable.range(1, 10).where(i => i % 3 == 0).select(i => i * 10);
```
As you can see, the linq.js version uses correct, lowercase methods.
