### ISSUE TITLE
comparison function for orderBy

### ISSUE THREAD

**Issue by mihaifm** [mihaifm/linq#74]
orderBy doesn't take a compare function as parameter, similar to [C# LINQ orderBy](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.orderby?view=netframework-4.8#System_Linq_Enumerable_OrderBy__2_System_Collections_Generic_IEnumerable___0__System_Func___0___1__System_Collections_Generic_IComparer___1__)

**Comment by zhongchengyi** [comment]
The following two methods have the same effect，but how to set `zh-cn` like `new Intl.Collator('zh-cn').compare('排','序');` >(https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Collator)
![image](https://user-images.githubusercontent.com/12371940/76282058-9b374900-62d1-11ea-8ca8-61c87a2fc952.png)
![image](https://user-images.githubusercontent.com/12371940/76282078-ae4a1900-62d1-11ea-83e3-0d56e18321e8.png)

**Comment by zhongchengyi** [comment]
The possible problems：
1. whether has `zh-cn` in other countries
2. how to solve browser compatibility

**Comment by mihaifm** [comment]
I've released a [new version](https://github.com/mihaifm/linq/releases/tag/3.2.2) to fix this.

You can now write

```
var a = ['中','文', '排', '序'];
linq.from(a).orderBy(x=>x, (x, y)=>x.localeCompare(y, 'zh-cn')).toArray()
```
Modern browsers seem to be fine since they include i18n support, I think only node.js may have issues if you're using a version without ICU support (see [here](https://nodejs.org/api/intl.html)). But if you're writing code for modern browsers you should be fine.
