### ISSUE TITLE
how to use left join?

### ISSUE THREAD

**Issue by caobingsheng** [mihaifm/linq#91]

**Comment by miquik** [comment]
You can do something like this:

`
    let results = Enumerable.from(arr1)
            .groupJoin(arr2,
                (outer) => outer.key,
                (inner) => inner.key,
                (outer, inner) => ({o:outer,i:inner}))
            .selectMany((xy) => xy.i.defaultIfEmpty(),
                (outer, inner) => ({o:outer.o,i:inner}))
            .select((x) => ({
                // your select
            }))
            .toArray()
`

**Comment by caobingsheng** [comment]
Thanks a lot
