### ISSUE TITLE
Transfer ownership of this package

### ISSUE THREAD

**Issue by Neuroboy23** [mihaifm/linq#97]
I see in the README that this is no longer maintained. I submitted a PR back in April which was merged. I would like to see this updated. Is there any plan for ownership of this package? I would like to take ownership if this has been abandoned.

**Comment by mihaifm** [comment]
The readme refers to the original version of the library which was developed ages ago.

This project is pretty much active. I just haven't released a new version to npm, I'll try to do that this weekend.

**Comment by mihaifm** [comment]
New version published

**Comment by Neuroboy23** [comment]
Thank you!
